#!/bin/sh

#Data that will populate ./forms/*.wcs ( not actually all *.wcs but only where is it needed)
FORM_PLONE_FOLDDER=""
FORM_URI_PLONE=""

# Data that will populate ./passerelle/export_plone-restapi_actualites.json
PASSERELLE_ACTUALITES_BASIC_AUTH_USERNAME=""
PASSERELLE_ACTUALITES_BASIC_AUTH_PW=""
PASSERELLE_ACTUALITES_SERVICE_URL="https://actualites.enwallonie.be"
PASSERELLE_ACTUALITES_TOKEN_WS_URL"https://agents.wallonie-connect.be/idp/oidc/token/"
PASSERELLE_ACTUALITES_CLIENT_ID=""
PASSERELLE_ACTUALITES_CLIENT_SECRET=""
PASSERELLE_ACTUALITES_USERNAME=""
PASSERELLE_ACTUALITES_PW=""
PASSERELLE_ACTUALITES_QUERIES_URI=""

# Data that will populate ./passerelle/export_plone-restapi_annuaire.json
PASSERELLE_ANNUAIRE_BASIC_AUTH_USERNAME=""
PASSERELLE_ANNUAIRE_BASIC_AUTH_PW=""
PASSERELLE_ANNUAIRE_SERVICE_URL="https://annuaire.enwallonie.be"
PASSERELLE_ANNUAIRE_TOKEN_URL="https://agents.wallonie-connect.be/idp/oidc/token/"
PASSERELLE_ANNUAIRE_CLIENT_ID=""
PASSERELLE_ANNUAIRE_CLIENT_SECRET=""
PASSERELLE_ANNUAIRE_USERNAME=""
PASSERELLE_ANNUAIRE_PW=""
PASSERELLE_ANNUAIRE_QUERIES_URI=""

# Data that will populate ./passerelle/export_plone-restapi_deliberations.json
PASSERELLE_DELIBERATIONS_BASIC_AUTH_USERNAME=""
PASSERELLE_DELIBERATIONS_BASIC_AUTH_PW=""
PASSERELLE_DELIBERATIONS_SERVICE_URL="https://www.deliberations.be"
PASSERELLE_DELIBERATIONS_TOKEN_URL=""
PASSERELLE_DELIBERATIONS_CLIENT_ID=""
PASSERELLE_DELIBERATIONS_CLIENT_SECRET=""
PASSERELLE_DELIBERATIONS_USERNAME=""
PASSERELLE_DELIBERATIONS_PW=""
PASSERELLE_DELIBERATIONS_QUERIES_URI=""


# Data that will populate ./passerelle/export_plone-restapi_evenements.json
PASSERELLE_EVENEMENTS_BASIC_AUTH_USERNAME=""
PASSERELLE_EVENEMENTS_BASIC_AUTH_PASSWORD=""
PASSERELLE_EVENEMENTS_SERVICE_URL="https://agenda.enwallonie.be"
PASSERELLE_EVENEMENTS_TOKEN_URL="https://agents.wallonie-connect.be/idp/oidc/token/"
PASSERELLE_EVENEMENTS_CLIENT_ID=""
PASSERELLE_EVENEMENTS_CLIENT_SECRET=""
PASSERELLE_EVENEMENTS_USERNAME=""
PASSERELLE_EVENEMENTS_PW=""
PASSERELLE_EVENEMENTS_QUERIES_URI=""

# Data that will populate ./passerelle/export_plone-restapi_site-web.json
PASSERELLE_SITE_WEB_BASIC_AUTH_USERNAME=""
PASSERELLE_SITE_WEB_BASIC_AUTH_PW=""
PASSERELLE_SITE_WEB_SERVICE_URL=""
PASSERELLE_SITE_WEB_TOKEN_URL=""
PASSERELLE_SITE_WEB_CLIENT_ID=""
PASSERELLE_SITE_WEB_CLIENT_SECRET=""
PASSERELLE_SITE_WEB_USERNAME=""
PASSERELLE_SITE_WEB_PW=""
PASSERELLE_SITE_WEB_QUERIES_URI=""

set -e # Exit immediately if a command exits with a non-zero status.

# installation path
install_path="/usr/lib/teleservices_iacitizen"

sudo -u hobo hobo-manage imio_indus_deploy --directory $install_path
